apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deploy-frontend-hpa
  namespace: aws-study-board
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-frontend # 프론트엔드 Deployment 타겟
  minReplicas: 2 # 최소 2개 유지 (고가용성)
  maxReplicas: 4 # 최대 4개까지 스케일 아웃
  metrics:
  # 1. CPU 메트릭: 성능 및 응답 속도 관리 (50%를 넘기면 스케일링 시작)
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # 2. 메모리 메트릭: 안정성 및 Crash 방지 (60%를 넘기면 스케일링 시작)
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
